# This file was generated by GoReleaser. DO NOT EDIT.
cask "calcmark" do
  version "1.9.13"

  on_macos do
    on_intel do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "77086538486af9cdb2a71c7714632de401147daf374bce12e34f8027285f9367"
    end
    on_arm do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "7bf691d0d48f3065a642793dfae57a00442837329e9296ad2c972fefd337d005"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_linux_amd64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "1f2f1f46cad9ccf1f0a816f5720e9d668ba29a8de58f33a6dcade7eb0950508b"
    end
    on_arm do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_linux_arm64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "488b9c83d7064968011e69e4c014c30bcc623887cc3f904e604598008c8dbf97"
    end
  end

  name "calcmark"
  desc "CalcMark - calculations embedded in markdown"
  homepage "https://calcmark.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cm"]
    end
  end

  # No zap stanza required

end
