# This file was generated by GoReleaser. DO NOT EDIT.
cask "calcmark" do
  version "1.13.2"

  on_macos do
    on_intel do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "394815151fa094401b6827bb6ea4ce24d51fe150eb377648758759161e74f886"
    end
    on_arm do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "8392d73f0b4c58927b4bd8985c65a6e9922bc6219e4a4b77243bdbdbc25d7646"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_linux_amd64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "e272a4065631b0017024e2083c58a598bf1cff234c1db4e867c278cefb525d68"
    end
    on_arm do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_linux_arm64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "c84af5de884d63c1e46739d357a0c6484361f9f7891e8370122b551ac2643708"
    end
  end

  name "calcmark"
  desc "CalcMark - calculations embedded in markdown"
  homepage "https://calcmark.org"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cm"]
    end
  end

  # No zap stanza required

end
