# This file was generated by GoReleaser. DO NOT EDIT.
cask "calcmark" do
  name "calcmark"
  desc "CalcMark - calculations embedded in markdown"
  homepage "https://calcmark.org"
  version "1.8.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cm"

  on_macos do
    on_intel do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "f7dfba017d4a16abaadf1f7d5295e5f0c7da04220a9f4367e29e4dc8012a96b5"
    end
    on_arm do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "1bab64c79aab53edbf2c2ec81fbfa691a608e3f18711593b198f3f8963b2bbcd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_linux_amd64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "15848261513059f72e0497e2835d03fd9e29146c28cd56f0647b9b18d08120cf"
    end
    on_arm do
      url "https://github.com/CalcMark/go-calcmark/releases/download/v#{version}/calcmark_#{version}_linux_arm64.tar.gz",
        verified: "github.com/CalcMark/go-calcmark"
      sha256 "fd28670178df83486399968351fa0fa8954ef5c5d91596304e396559272440f2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cm"]
    end
  end

  # No zap stanza required
end
