# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calcmark < Formula
  desc "CalcMark - calculations embedded in markdown"
  homepage "https://github.com/CalcMark/go-calcmark"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/CalcMark/go-calcmark/releases/download/v1.1.0/calcmark_1.1.0_darwin_amd64.tar.gz"
      sha256 "f412bc3103d91c710d37d1f3ce64f6381a3eb54c8bb167749c152c50219e6bf0"

      define_method(:install) do
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/CalcMark/go-calcmark/releases/download/v1.1.0/calcmark_1.1.0_darwin_arm64.tar.gz"
      sha256 "ed3acc5c49e40431603a885d88b7f03c22eace74f22ce58466f3355acf135c7a"

      define_method(:install) do
        bin.install "cm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/CalcMark/go-calcmark/releases/download/v1.1.0/calcmark_1.1.0_linux_amd64.tar.gz"
      sha256 "025c7f27d6210112e69aef0b9cf00d50dda44ed9314cdb6a4ef84f13b2e3b06e"
      define_method(:install) do
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/CalcMark/go-calcmark/releases/download/v1.1.0/calcmark_1.1.0_linux_armv6.tar.gz"
      sha256 "3c4a2f350acc0edfddbd6ec74fecb9e6e8bc6b7fd27781a21444483bb1771599"
      define_method(:install) do
        bin.install "cm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/CalcMark/go-calcmark/releases/download/v1.1.0/calcmark_1.1.0_linux_arm64.tar.gz"
      sha256 "5752b434d0f248fd058759326690b2ed1f4c8cd43ba67de6bb692331eb0e398f"
      define_method(:install) do
        bin.install "cm"
      end
    end
  end

  test do
    system "#{bin}/cm", "version"
  end
end
